label chapter_1_1_1_3:
    $ renpy.block_rollback()
    Chara "......。"
    Flowey "* 「啊啊太好了！！妳就把我放到妳頭上吧！」"
    Chara "* ......？"
    Narration "* Chara 遲疑地看著小花，比了幾個手勢。"
    Flowey "* 「妳把手伸過來。」"
    Narration "* Chara 向小花伸出她唯一的那隻手。"
    Narration "* 小花伸出他的藤蔓，捲到 Chara 的手臂上，等待對方地將自己移到頭頂。"
    Narration "* 藤蔓輕輕穿過 Chara 的髮絲，小花最終將自己固定在她的頭髮上。"
    Flowey "* 「鏘鏘！就當我是妳的髮箍吧，妳會不會不舒服？」"
    Chara "* 「......。」"
    Chara "* 比了幾個手勢。"
    Flowey "* 「有點癢是嗎？那這樣呢？」"
    Narration "* 她挪了挪位置。"
    Chara "* 「......。」"
    Flowey "* 「那就好！如果我們找到鏡子的話，我可以再把位置喬好看一點。」"
    Chara "* 「......////。」"
    Flowey "* 「但我喜歡看妳漂漂亮亮的樣子嘛！哈哈哈哈......{w=0.2}對了！這個給妳。」"
    Narration "* 小花用藤蔓推了推突然出現在 Chara 眼前、有些破碎的重置鍵。"
    Flowey "* 「我覺得妳能用的比我好。」"
    Chara "「......。」"
    Narration "* 她觸碰橘色的按鍵，感覺到它歸屬於自己。"
    Flowey "* 「如果你看得差不多了，那就上路吧？」"

    jump chapter_1_1_1_1